
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action Action;

	private global::Gtk.Action Action1;

	private global::Gtk.Action Action2;

	private global::Gtk.Action Action3;

	private global::Gtk.Action Action4;

	private global::Gtk.Action HexagonAction;

	private global::Gtk.Action Action5;

	private global::Gtk.Action Action6;

	private global::Gtk.Action Action7;

	private global::Gtk.Action Action11;

	private global::Gtk.Action Action9;

	private global::Gtk.Action Action10;

	private global::Gtk.Action Action29;

	private global::Gtk.Action Action15;

	private global::Gtk.Action Action28;

	private global::Gtk.Action Action16;

	private global::Gtk.Action HexagonAction1;

	private global::Gtk.Action Action17;

	private global::Gtk.Action Action23;

	private global::Gtk.Action Action19;

	private global::Gtk.Action Action20;

	private global::Gtk.Action Action21;

	private global::Gtk.Action Action22;

	private global::Gtk.Action Action24;

	private global::Gtk.Action Action25;

	private global::Gtk.Action Action30;

	private global::Gtk.VBox vbox4;

	private global::Gtk.MenuBar menubar7;

	private global::Gtk.DrawingArea drawingArea;

	private global::Gtk.HBox hbox19;

	private global::Gtk.HBox hbox21;

	private global::Gtk.Label time;

	private global::Gtk.Label numberOfFlags;

	private global::Gtk.HBox hbox23;

	private global::Gtk.CheckButton putUpFlags;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.Action = new global::Gtk.Action("Action", global::Mono.Unix.Catalog.GetString("Игра"), null, null);
		this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString("Игра");
		w1.Add(this.Action, null);
		this.Action1 = new global::Gtk.Action("Action1", global::Mono.Unix.Catalog.GetString("Справка"), null, null);
		this.Action1.ShortLabel = global::Mono.Unix.Catalog.GetString("Справка");
		w1.Add(this.Action1, null);
		this.Action2 = new global::Gtk.Action("Action2", global::Mono.Unix.Catalog.GetString("Правила игры"), null, null);
		this.Action2.ShortLabel = global::Mono.Unix.Catalog.GetString("Правила игры");
		w1.Add(this.Action2, null);
		this.Action3 = new global::Gtk.Action("Action3", global::Mono.Unix.Catalog.GetString("Новая игра"), null, null);
		this.Action3.ShortLabel = global::Mono.Unix.Catalog.GetString("Новая игра");
		w1.Add(this.Action3, null);
		this.Action4 = new global::Gtk.Action("Action4", global::Mono.Unix.Catalog.GetString("Классический режим"), null, null);
		this.Action4.ShortLabel = global::Mono.Unix.Catalog.GetString("Классический режим");
		w1.Add(this.Action4, null);
		this.HexagonAction = new global::Gtk.Action("HexagonAction", global::Mono.Unix.Catalog.GetString("Hexagon режим"), null, null);
		this.HexagonAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Hexagon режим");
		w1.Add(this.HexagonAction, null);
		this.Action5 = new global::Gtk.Action("Action5", global::Mono.Unix.Catalog.GetString("Низкая сложность"), null, null);
		this.Action5.ShortLabel = global::Mono.Unix.Catalog.GetString("Низкая сложность");
		w1.Add(this.Action5, null);
		this.Action6 = new global::Gtk.Action("Action6", global::Mono.Unix.Catalog.GetString("Средняя сложность"), null, null);
		this.Action6.ShortLabel = global::Mono.Unix.Catalog.GetString("Средняя сложность");
		w1.Add(this.Action6, null);
		this.Action7 = new global::Gtk.Action("Action7", global::Mono.Unix.Catalog.GetString("Высокая сложность"), null, null);
		this.Action7.ShortLabel = global::Mono.Unix.Catalog.GetString("Высокая сложность");
		w1.Add(this.Action7, null);
		this.Action11 = new global::Gtk.Action("Action11", global::Mono.Unix.Catalog.GetString("Низкая сложность"), null, null);
		this.Action11.ShortLabel = global::Mono.Unix.Catalog.GetString("Низкая сложность");
		w1.Add(this.Action11, null);
		this.Action9 = new global::Gtk.Action("Action9", global::Mono.Unix.Catalog.GetString("Средняя сложность"), null, null);
		this.Action9.ShortLabel = global::Mono.Unix.Catalog.GetString("Средняя сложность");
		w1.Add(this.Action9, null);
		this.Action10 = new global::Gtk.Action("Action10", global::Mono.Unix.Catalog.GetString("Высокая сложность"), null, null);
		this.Action10.ShortLabel = global::Mono.Unix.Catalog.GetString("Высокая сложность");
		w1.Add(this.Action10, null);
		this.Action29 = new global::Gtk.Action("Action29", global::Mono.Unix.Catalog.GetString("Игра"), null, null);
		this.Action29.ShortLabel = global::Mono.Unix.Catalog.GetString("Игра");
		w1.Add(this.Action29, null);
		this.Action15 = new global::Gtk.Action("Action15", global::Mono.Unix.Catalog.GetString("Новая игра"), null, null);
		this.Action15.ShortLabel = global::Mono.Unix.Catalog.GetString("Новая игра");
		w1.Add(this.Action15, null);
		this.Action28 = new global::Gtk.Action("Action28", global::Mono.Unix.Catalog.GetString("Рекорды"), null, null);
		this.Action28.ShortLabel = global::Mono.Unix.Catalog.GetString("Рекорды");
		w1.Add(this.Action28, null);
		this.Action16 = new global::Gtk.Action("Action16", global::Mono.Unix.Catalog.GetString("Классический режим"), null, null);
		this.Action16.ShortLabel = global::Mono.Unix.Catalog.GetString("Классический режим");
		w1.Add(this.Action16, null);
		this.HexagonAction1 = new global::Gtk.Action("HexagonAction1", global::Mono.Unix.Catalog.GetString("Hexagon режим"), null, null);
		this.HexagonAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Hexagon режим");
		w1.Add(this.HexagonAction1, null);
		this.Action17 = new global::Gtk.Action("Action17", global::Mono.Unix.Catalog.GetString("Легкая сложность"), null, null);
		this.Action17.ShortLabel = global::Mono.Unix.Catalog.GetString("Легкая сложность");
		w1.Add(this.Action17, null);
		this.Action23 = new global::Gtk.Action("Action23", global::Mono.Unix.Catalog.GetString("Средняя сложность"), null, null);
		this.Action23.ShortLabel = global::Mono.Unix.Catalog.GetString("Средняя сложность");
		w1.Add(this.Action23, null);
		this.Action19 = new global::Gtk.Action("Action19", global::Mono.Unix.Catalog.GetString("Высокая сложность"), null, null);
		this.Action19.ShortLabel = global::Mono.Unix.Catalog.GetString("Высокая сложность");
		w1.Add(this.Action19, null);
		this.Action20 = new global::Gtk.Action("Action20", global::Mono.Unix.Catalog.GetString("Легкая сложность"), null, null);
		this.Action20.ShortLabel = global::Mono.Unix.Catalog.GetString("Легкая сложность");
		w1.Add(this.Action20, null);
		this.Action21 = new global::Gtk.Action("Action21", global::Mono.Unix.Catalog.GetString("Средняя сложность"), null, null);
		this.Action21.ShortLabel = global::Mono.Unix.Catalog.GetString("Средняя сложность");
		w1.Add(this.Action21, null);
		this.Action22 = new global::Gtk.Action("Action22", global::Mono.Unix.Catalog.GetString("Высокая сложность"), null, null);
		this.Action22.ShortLabel = global::Mono.Unix.Catalog.GetString("Высокая сложность");
		w1.Add(this.Action22, null);
		this.Action24 = new global::Gtk.Action("Action24", global::Mono.Unix.Catalog.GetString("Справка"), null, null);
		this.Action24.ShortLabel = global::Mono.Unix.Catalog.GetString("Справка");
		w1.Add(this.Action24, null);
		this.Action25 = new global::Gtk.Action("Action25", global::Mono.Unix.Catalog.GetString("Правила игры"), null, null);
		this.Action25.ShortLabel = global::Mono.Unix.Catalog.GetString("Правила игры");
		w1.Add(this.Action25, null);
		this.Action30 = new global::Gtk.Action("Action30", global::Mono.Unix.Catalog.GetString("О программе"), null, null);
		this.Action30.ShortLabel = global::Mono.Unix.Catalog.GetString("Об авторе");
		w1.Add(this.Action30, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("И508Б Снегирев С.И. \"Сапёр\"");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar7'><menu name='Action29' action='Action29'><menu name='Action15' action='Action15'><menu name='Action16' action='Action16'><menuitem name='Action17' action='Action17'/><menuitem name='Action23' action='Action23'/><menuitem name='Action19' action='Action19'/></menu><menu name='HexagonAction1' action='HexagonAction1'><menuitem name='Action20' action='Action20'/><menuitem name='Action21' action='Action21'/><menuitem name='Action22' action='Action22'/></menu></menu><menuitem name='Action28' action='Action28'/></menu><menu name='Action24' action='Action24'><menuitem name='Action25' action='Action25'/><menuitem name='Action30' action='Action30'/></menu></menubar></ui>");
		this.menubar7 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar7")));
		this.menubar7.Name = "menubar7";
		this.vbox4.Add(this.menubar7);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.menubar7]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.drawingArea = new global::Gtk.DrawingArea();
		this.drawingArea.Name = "drawingArea";
		this.vbox4.Add(this.drawingArea);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.drawingArea]));
		w3.Position = 1;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox19 = new global::Gtk.HBox();
		this.hbox19.Name = "hbox19";
		this.hbox19.Spacing = 6;
		// Container child hbox19.Gtk.Box+BoxChild
		this.hbox21 = new global::Gtk.HBox();
		this.hbox21.Name = "hbox21";
		this.hbox21.Spacing = 6;
		// Container child hbox21.Gtk.Box+BoxChild
		this.time = new global::Gtk.Label();
		this.time.WidthRequest = 250;
		this.time.Name = "time";
		this.time.LabelProp = global::Mono.Unix.Catalog.GetString("Время: ");
		this.time.Justify = ((global::Gtk.Justification)(2));
		this.hbox21.Add(this.time);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.time]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox21.Gtk.Box+BoxChild
		this.numberOfFlags = new global::Gtk.Label();
		this.numberOfFlags.WidthRequest = 220;
		this.numberOfFlags.Name = "numberOfFlags";
		this.numberOfFlags.LabelProp = global::Mono.Unix.Catalog.GetString("Количество мин:");
		this.hbox21.Add(this.numberOfFlags);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.numberOfFlags]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.hbox19.Add(this.hbox21);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.hbox21]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox19.Gtk.Box+BoxChild
		this.hbox23 = new global::Gtk.HBox();
		this.hbox23.Name = "hbox23";
		this.hbox23.Spacing = 6;
		// Container child hbox23.Gtk.Box+BoxChild
		this.putUpFlags = new global::Gtk.CheckButton();
		this.putUpFlags.WidthRequest = 120;
		this.putUpFlags.CanFocus = true;
		this.putUpFlags.Name = "putUpFlags";
		this.putUpFlags.Label = global::Mono.Unix.Catalog.GetString("Расставить флаги");
		this.putUpFlags.DrawIndicator = true;
		this.putUpFlags.UseUnderline = true;
		this.hbox23.Add(this.putUpFlags);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.putUpFlags]));
		w7.Position = 0;
		this.hbox19.Add(this.hbox23);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.hbox23]));
		w8.Position = 1;
		this.vbox4.Add(this.hbox19);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox19]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.Add(this.vbox4);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 700;
		this.DefaultHeight = 726;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.Action5.Activated += new global::System.EventHandler(this.OnClassicModeEasy);
		this.Action6.Activated += new global::System.EventHandler(this.OnClassicModeMedium);
		this.Action7.Activated += new global::System.EventHandler(this.OnClassicModeHard);
		this.Action11.Activated += new global::System.EventHandler(this.OnHexagonModeEasy);
		this.Action9.Activated += new global::System.EventHandler(this.OnHexagonModeMedium);
		this.Action10.Activated += new global::System.EventHandler(this.OnHexagonModeHard);
		this.Action28.Activated += new global::System.EventHandler(this.OnRecords);
		this.Action17.Activated += new global::System.EventHandler(this.OnClassicModeEasy);
		this.Action23.Activated += new global::System.EventHandler(this.OnClassicModeMedium);
		this.Action19.Activated += new global::System.EventHandler(this.OnClassicModeHard);
		this.Action20.Activated += new global::System.EventHandler(this.OnHexagonModeEasy);
		this.Action21.Activated += new global::System.EventHandler(this.OnHexagonModeMedium);
		this.Action22.Activated += new global::System.EventHandler(this.OnHexagonModeHard);
		this.Action25.Activated += new global::System.EventHandler(this.OnRules);
		this.Action30.Activated += new global::System.EventHandler(this.OnAboutAutor);
		this.drawingArea.ExposeEvent += new global::Gtk.ExposeEventHandler(this.OnDrawingExposeEvent);
	}
}
