
// This file has been generated by the GUI designer. Do not modify.
namespace Minesweeper
{
	public partial class Records
	{
		private global::Gtk.ScrolledWindow scrolledwindow2;

		private global::Gtk.HBox hbox4;

		private global::Gtk.VSeparator vseparator3;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HSeparator hseparator5;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label1;

		private global::Gtk.Label label3;

		private global::Gtk.HSeparator hseparator9;

		private global::Gtk.HBox hbox7;

		private global::Gtk.HBox hbox19;

		private global::Gtk.VBox vbox17;

		private global::Gtk.Label label2;

		private global::Gtk.HSeparator hseparator21;

		private global::Gtk.Label labelClassicModeEasy;

		private global::Gtk.VSeparator vseparator23;

		private global::Gtk.VBox vbox15;

		private global::Gtk.Label label4;

		private global::Gtk.HSeparator hseparator19;

		private global::Gtk.Label labelClassicModeMedium;

		private global::Gtk.HBox hbox9;

		private global::Gtk.VSeparator vseparator25;

		private global::Gtk.HBox hbox21;

		private global::Gtk.VBox vbox13;

		private global::Gtk.Label label6;

		private global::Gtk.HSeparator hseparator17;

		private global::Gtk.Label labelClassicModeHard;

		private global::Gtk.VSeparator vseparator17;

		private global::Gtk.VBox vbox11;

		private global::Gtk.Label label9;

		private global::Gtk.HSeparator hseparator15;

		private global::Gtk.Label labelHexagonModeEasy;

		private global::Gtk.VSeparator vseparator19;

		private global::Gtk.HBox hbox17;

		private global::Gtk.VBox vbox9;

		private global::Gtk.Label label7;

		private global::Gtk.HSeparator hseparator13;

		private global::Gtk.Label labelHexagonModeMedium;

		private global::Gtk.VSeparator vseparator21;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Label label5;

		private global::Gtk.HSeparator hseparator11;

		private global::Gtk.Label labelHexagonModeHard;

		private global::Gtk.HSeparator hseparator7;

		private global::Gtk.VSeparator vseparator1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Minesweeper.Records
			this.WidthRequest = 6;
			this.HeightRequest = 400;
			this.Name = "Minesweeper.Records";
			this.Title = global::Mono.Unix.Catalog.GetString("Таблица рекордов");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child Minesweeper.Records.Gtk.Container+ContainerChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator();
			this.vseparator3.Name = "vseparator3";
			this.hbox4.Add(this.vseparator3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vseparator3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator5 = new global::Gtk.HSeparator();
			this.hseparator5.Name = "hseparator5";
			this.vbox3.Add(this.hseparator5);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hseparator5]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.Xpad = 118;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Классический режим");
			this.label1.Justify = ((global::Gtk.Justification)(2));
			this.hbox5.Add(this.label1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Xpad = 119;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Hexagon режим");
			this.label3.Justify = ((global::Gtk.Justification)(2));
			this.hbox5.Add(this.label3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label3]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox5.Add(this.hbox5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox5]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hseparator9 = new global::Gtk.HSeparator();
			this.hseparator9.Name = "hseparator9";
			this.vbox5.Add(this.hseparator9);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hseparator9]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.vbox17 = new global::Gtk.VBox();
			this.vbox17.Name = "vbox17";
			this.vbox17.Spacing = 6;
			// Container child vbox17.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Легкая сложность");
			this.label2.Justify = ((global::Gtk.Justification)(2));
			this.vbox17.Add(this.label2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.label2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox17.Gtk.Box+BoxChild
			this.hseparator21 = new global::Gtk.HSeparator();
			this.hseparator21.Name = "hseparator21";
			this.vbox17.Add(this.hseparator21);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.hseparator21]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox17.Gtk.Box+BoxChild
			this.labelClassicModeEasy = new global::Gtk.Label();
			this.labelClassicModeEasy.Name = "labelClassicModeEasy";
			this.labelClassicModeEasy.LabelProp = global::Mono.Unix.Catalog.GetString("-");
			this.vbox17.Add(this.labelClassicModeEasy);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.labelClassicModeEasy]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.hbox19.Add(this.vbox17);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.vbox17]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.vseparator23 = new global::Gtk.VSeparator();
			this.vseparator23.Name = "vseparator23";
			this.hbox19.Add(this.vseparator23);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.vseparator23]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.vbox15 = new global::Gtk.VBox();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Средняя сложность");
			this.vbox15.Add(this.label4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.label4]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hseparator19 = new global::Gtk.HSeparator();
			this.hseparator19.Name = "hseparator19";
			this.vbox15.Add(this.hseparator19);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.hseparator19]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.labelClassicModeMedium = new global::Gtk.Label();
			this.labelClassicModeMedium.Name = "labelClassicModeMedium";
			this.labelClassicModeMedium.LabelProp = global::Mono.Unix.Catalog.GetString("-");
			this.vbox15.Add(this.labelClassicModeMedium);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.labelClassicModeMedium]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.hbox19.Add(this.vbox15);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.vbox15]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			this.hbox7.Add(this.hbox19);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.hbox19]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vseparator25 = new global::Gtk.VSeparator();
			this.vseparator25.Name = "vseparator25";
			this.hbox9.Add(this.vseparator25);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vseparator25]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Высокая сложность");
			this.label6.Justify = ((global::Gtk.Justification)(2));
			this.vbox13.Add(this.label6);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.label6]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.hseparator17 = new global::Gtk.HSeparator();
			this.hseparator17.Name = "hseparator17";
			this.vbox13.Add(this.hseparator17);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.hseparator17]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.labelClassicModeHard = new global::Gtk.Label();
			this.labelClassicModeHard.Name = "labelClassicModeHard";
			this.labelClassicModeHard.LabelProp = global::Mono.Unix.Catalog.GetString("-");
			this.vbox13.Add(this.labelClassicModeHard);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.labelClassicModeHard]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			this.hbox21.Add(this.vbox13);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.vbox13]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.vseparator17 = new global::Gtk.VSeparator();
			this.vseparator17.Name = "vseparator17";
			this.hbox21.Add(this.vseparator17);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.vseparator17]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Легкая сложность");
			this.label9.Justify = ((global::Gtk.Justification)(2));
			this.vbox11.Add(this.label9);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.label9]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hseparator15 = new global::Gtk.HSeparator();
			this.hseparator15.Name = "hseparator15";
			this.vbox11.Add(this.hseparator15);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hseparator15]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.labelHexagonModeEasy = new global::Gtk.Label();
			this.labelHexagonModeEasy.Name = "labelHexagonModeEasy";
			this.labelHexagonModeEasy.LabelProp = global::Mono.Unix.Catalog.GetString("-");
			this.vbox11.Add(this.labelHexagonModeEasy);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.labelHexagonModeEasy]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			this.hbox21.Add(this.vbox11);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.vbox11]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.hbox9.Add(this.hbox21);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.hbox21]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vseparator19 = new global::Gtk.VSeparator();
			this.vseparator19.Name = "vseparator19";
			this.hbox9.Add(this.vseparator19);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vseparator19]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			this.hbox7.Add(this.hbox9);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.hbox9]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Средняя сложность");
			this.label7.Justify = ((global::Gtk.Justification)(2));
			this.vbox9.Add(this.label7);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label7]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hseparator13 = new global::Gtk.HSeparator();
			this.hseparator13.Name = "hseparator13";
			this.vbox9.Add(this.hseparator13);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hseparator13]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.labelHexagonModeMedium = new global::Gtk.Label();
			this.labelHexagonModeMedium.Name = "labelHexagonModeMedium";
			this.labelHexagonModeMedium.LabelProp = global::Mono.Unix.Catalog.GetString("-");
			this.vbox9.Add(this.labelHexagonModeMedium);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.labelHexagonModeMedium]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			this.hbox17.Add(this.vbox9);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.vbox9]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.vseparator21 = new global::Gtk.VSeparator();
			this.vseparator21.Name = "vseparator21";
			this.hbox17.Add(this.vseparator21);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.vseparator21]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Высокая сложность");
			this.label5.Justify = ((global::Gtk.Justification)(2));
			this.vbox7.Add(this.label5);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label5]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hseparator11 = new global::Gtk.HSeparator();
			this.hseparator11.Name = "hseparator11";
			this.vbox7.Add(this.hseparator11);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hseparator11]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.labelHexagonModeHard = new global::Gtk.Label();
			this.labelHexagonModeHard.Name = "labelHexagonModeHard";
			this.labelHexagonModeHard.LabelProp = global::Mono.Unix.Catalog.GetString("-");
			this.vbox7.Add(this.labelHexagonModeHard);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.labelHexagonModeHard]));
			w38.Position = 2;
			w38.Expand = false;
			w38.Fill = false;
			this.hbox17.Add(this.vbox7);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.vbox7]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			this.hbox7.Add(this.hbox17);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.hbox17]));
			w40.Position = 2;
			w40.Expand = false;
			w40.Fill = false;
			this.vbox5.Add(this.hbox7);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
			w41.Position = 2;
			w41.Expand = false;
			w41.Fill = false;
			this.vbox3.Add(this.vbox5);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox5]));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator7 = new global::Gtk.HSeparator();
			this.hseparator7.Name = "hseparator7";
			this.vbox3.Add(this.hseparator7);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hseparator7]));
			w43.Position = 2;
			w43.Expand = false;
			w43.Fill = false;
			this.hbox4.Add(this.vbox3);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox3]));
			w44.Position = 1;
			w44.Expand = false;
			w44.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator();
			this.vseparator1.Name = "vseparator1";
			this.hbox4.Add(this.vseparator1);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vseparator1]));
			w45.Position = 2;
			w45.Expand = false;
			w45.Fill = false;
			w1.Add(this.hbox4);
			this.scrolledwindow2.Add(w1);
			this.Add(this.scrolledwindow2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 757;
			this.DefaultHeight = 400;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		}
	}
}
