
// This file has been generated by the GUI designer. Do not modify.
namespace Minesweeper
{
	public partial class RulesWindow
	{
		private global::Gtk.Fixed fixed6;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Minesweeper.RulesWindow
			this.Name = "Minesweeper.RulesWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Правила игры");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			// Container child Minesweeper.RulesWindow.Gtk.Container+ContainerChild
			this.fixed6 = new global::Gtk.Fixed();
			this.fixed6.Name = "fixed6";
			this.fixed6.HasWindow = false;
			this.Add(this.fixed6);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
