
// This file has been generated by the GUI designer. Do not modify.
namespace Minesweeper
{
	public partial class DefeatWindow
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label defeatWindowLabel;

		private global::Gtk.Table table1;

		private global::Gtk.Button button19;

		private global::Gtk.DrawingArea drawingarea11;

		private global::Gtk.DrawingArea drawingarea13;

		private global::Gtk.DrawingArea drawingarea15;

		private global::Gtk.DrawingArea drawingarea17;

		private global::Gtk.DrawingArea drawingarea19;

		private global::Gtk.DrawingArea drawingarea5;

		private global::Gtk.DrawingArea drawingarea7;

		private global::Gtk.DrawingArea drawingarea9;

		private global::Stetic.Custom custom1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Minesweeper.DefeatWindow
			this.WidthRequest = 250;
			this.HeightRequest = 250;
			this.Name = "Minesweeper.DefeatWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Поражение");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Minesweeper.DefeatWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.defeatWindowLabel = new global::Gtk.Label();
			this.defeatWindowLabel.WidthRequest = 250;
			this.defeatWindowLabel.HeightRequest = 200;
			this.defeatWindowLabel.Name = "defeatWindowLabel";
			this.defeatWindowLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Вы проиграли!\n\nНажмите OK, чтобы начать заново.");
			this.defeatWindowLabel.Justify = ((global::Gtk.Justification)(2));
			this.vbox2.Add(this.defeatWindowLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.defeatWindowLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.button19 = new global::Gtk.Button();
			this.button19.WidthRequest = 100;
			this.button19.HeightRequest = 30;
			this.button19.CanFocus = true;
			this.button19.Name = "button19";
			this.button19.UseUnderline = true;
			this.button19.Label = global::Mono.Unix.Catalog.GetString("ОК");
			this.table1.Add(this.button19);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.button19]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea11 = new global::Gtk.DrawingArea();
			this.drawingarea11.Name = "drawingarea11";
			this.table1.Add(this.drawingarea11);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.drawingarea11]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea13 = new global::Gtk.DrawingArea();
			this.drawingarea13.Name = "drawingarea13";
			this.table1.Add(this.drawingarea13);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.drawingarea13]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(2));
			w4.RightAttach = ((uint)(3));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea15 = new global::Gtk.DrawingArea();
			this.drawingarea15.Name = "drawingarea15";
			this.table1.Add(this.drawingarea15);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.drawingarea15]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(2));
			w5.RightAttach = ((uint)(3));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea17 = new global::Gtk.DrawingArea();
			this.drawingarea17.Name = "drawingarea17";
			this.table1.Add(this.drawingarea17);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.drawingarea17]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea19 = new global::Gtk.DrawingArea();
			this.drawingarea19.Name = "drawingarea19";
			this.table1.Add(this.drawingarea19);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.drawingarea19]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea5 = new global::Gtk.DrawingArea();
			this.drawingarea5.Name = "drawingarea5";
			this.table1.Add(this.drawingarea5);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.drawingarea5]));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea7 = new global::Gtk.DrawingArea();
			this.drawingarea7.Name = "drawingarea7";
			this.table1.Add(this.drawingarea7);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.drawingarea7]));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea9 = new global::Gtk.DrawingArea();
			this.drawingarea9.Name = "drawingarea9";
			this.table1.Add(this.drawingarea9);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.drawingarea9]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			this.vbox2.Add(this.table1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.table1]));
			w11.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.custom1 = new global::Stetic.Custom();
			this.custom1.Name = "custom1";
			this.custom1.Int1 = 0;
			this.custom1.Int2 = 0;
			this.vbox2.Add(this.custom1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.custom1]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 312;
			this.DefaultHeight = 304;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.button19.Clicked += new global::System.EventHandler(this.OnClicked);
		}
	}
}
